[package]
name = "authtoken"
version = "0.1.0"
authors = ["Stephen James <sjames@examsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
josekit = "0.7.0"
serde = "1.0"
serde_json = "1.0"
dotenv = "0.15.0"